spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: provider-admin
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.198.147:8848

server:
  port: 11000

management:
  endpoints:
    web:
      exposure:
        include: "*"