spring:
  main:
    allow-bean-definition-overriding: true
  application:
    #服务名
    name: business-admin
  cloud:
    nacos:
      discovery:
        #服务注册中心
        server-addr: 192.168.198.147:8848

server:
  #服务端口
  port: 12000

management:
  #端口检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"